# Generated by Django 4.0.4 on 2022-05-04 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datepy_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
